In [3]:
import numpy as np


arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
# Create a 1D array of numbers from 0 to 9 and find the maximum and minimum values in the array.

arr1=np.arange(10)
print(arr1)
print("maximum",arr1.max())
print("minimum",arr1.min() )

[0 1 2 3 4 5 6 7 8 9]
maximum 9
minimum 0


In [13]:
# Create a 2D array of size 3x3 filled with random integers and calculate its mean, median, and standard deviation

arr2=np.random.randint(1,10,size=(3,3))
print(arr2)
print("mean",arr2.mean())
print("median",np.median(arr2))
print("std deviation",arr2.std())

[[8 8 1]
 [4 7 4]
 [9 3 1]]
mean 5.0
median 4.0
std deviation 2.9059326290271157


In [40]:
import numpy as np

# Create an array of zeros with shape 4x2
zero = np.zeros((4,4))
print("zeros array:\n", zero)

# Create an array of ones with shape 5x2
ones_array = np.ones((5, 4))
print("ones array:\n", ones_array)

# Concatenate vertically
concatenated_array = np.vstack((zero, ones_array))
print("concatenated array:\n", concatenated_array)


zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
concatenated array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [54]:
# Create a 1D array of even numbers between 10 and 30, replace all even numbers in it with -1, and reverse the modified array.

even_numbers=np.arange(10,31,2)
even_numbers[even_numbers % 2 == 0] = -1
even_numbers=even_numbers[::-1]
print(even_numbers)


[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
